         // This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

         export const commands = {
async readMetadata(file: string) : Promise<Metadata> {
return await TAURI_INVOKE("read_metadata", { file });
},
async selectMusicFolder() : Promise<Metadata[]> {
return await TAURI_INVOKE("select_music_folder");
},
async getSqlite() : Promise<string> {
return await TAURI_INVOKE("get_sqlite");
},
async getAlbumWithTracks(id: number) : Promise<AlbumWithTracks> {
return await TAURI_INVOKE("get_album_with_tracks", { id });
},
async getArtistWithAlbums(id: number) : Promise<ArtistWithAlbums> {
return await TAURI_INVOKE("get_artist_with_albums", { id });
},
async getAllAlbums() : Promise<Albums[]> {
return await TAURI_INVOKE("get_all_albums");
}
}



/** user-defined types **/

export type AlbumWithTracks = { album: Albums; tracks: Tracks[] }
export type Albums = { id: number; artists_id: number; artist: string; name: string; cover_path: string; album_type: string; duration: number; track_count: number; year: number; path: string }
export type ArtistWithAlbums = { artist: Artists; albums: AlbumWithTracks[] }
export type Artists = { id: number; name: string; path: string }
export type Metadata = { duration: number; album: string; artist: string; name: string; path: string; album_type: string; year: number }
export type Tracks = { id: number; duration: number; album: string; albums_id: number; artist: string; name: string; path: string }

/** tauri-specta globals **/

         import { invoke as TAURI_INVOKE } from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
  listen: (
    cb: TAURI_API_EVENT.EventCallback<T>
  ) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
  once: (
    cb: TAURI_API_EVENT.EventCallback<T>
  ) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
  emit: T extends null
    ? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
    : (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
  | { status: "ok"; data: T }
  | { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
  mappings: Record<keyof T, string>
) {
  return new Proxy(
    {} as unknown as {
      [K in keyof T]: __EventObj__<T[K]> & {
        (handle: __WebviewWindow__): __EventObj__<T[K]>;
      };
    },
    {
      get: (_, event) => {
        const name = mappings[event as keyof T];

        return new Proxy((() => {}) as any, {
          apply: (_, __, [window]: [__WebviewWindow__]) => ({
            listen: (arg: any) => window.listen(name, arg),
            once: (arg: any) => window.once(name, arg),
            emit: (arg: any) => window.emit(name, arg),
          }),
          get: (_, command: keyof __EventObj__<any>) => {
            switch (command) {
              case "listen":
                return (arg: any) => TAURI_API_EVENT.listen(name, arg);
              case "once":
                return (arg: any) => TAURI_API_EVENT.once(name, arg);
              case "emit":
                return (arg: any) => TAURI_API_EVENT.emit(name, arg);
            }
          },
        });
      },
    }
  );
}

     