
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async selectMusicFolder() : Promise<void> {
    await TAURI_INVOKE("select_music_folder");
},
async getAlbumWithTracks(id: number) : Promise<AlbumWithTracks> {
    return await TAURI_INVOKE("get_album_with_tracks", { id });
},
async getArtistWithAlbums(id: number) : Promise<ArtistWithAlbums> {
    return await TAURI_INVOKE("get_artist_with_albums", { id });
},
async getAllAlbums() : Promise<Albums[]> {
    return await TAURI_INVOKE("get_all_albums");
},
async trackById(id: number) : Promise<Tracks> {
    return await TAURI_INVOKE("track_by_id", { id });
},
async playTrack(trackId: number) : Promise<void> {
    await TAURI_INVOKE("play_track", { trackId });
},
async pauseTrack() : Promise<void> {
    await TAURI_INVOKE("pause_track");
},
async resumeTrack() : Promise<void> {
    await TAURI_INVOKE("resume_track");
},
async seekTrack(position: number, resume: boolean) : Promise<void> {
    await TAURI_INVOKE("seek_track", { position, resume });
},
async setVolume(volume: number) : Promise<void> {
    await TAURI_INVOKE("set_volume", { volume });
},
async getPlayerState() : Promise<PlayerState> {
    return await TAURI_INVOKE("get_player_state");
},
async playerHasTrack() : Promise<boolean> {
    return await TAURI_INVOKE("player_has_track");
},
async getPlayerProgress() : Promise<number> {
    return await TAURI_INVOKE("get_player_progress");
},
async getPlayerDuration() : Promise<number> {
    return await TAURI_INVOKE("get_player_duration");
},
async stopPlayer() : Promise<void> {
    await TAURI_INVOKE("stop_player");
},
async updateProgress() : Promise<void> {
    await TAURI_INVOKE("update_progress");
},
async initializePlayer(trackId: number, progress: number) : Promise<void> {
    await TAURI_INVOKE("initialize_player", { trackId, progress });
},
async setPlayerProgress(progress: number) : Promise<void> {
    await TAURI_INVOKE("set_player_progress", { progress });
},
async playerHasEnded() : Promise<boolean> {
    return await TAURI_INVOKE("player_has_ended");
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AlbumWithTracks = { album: Albums; tracks: Tracks[] }
export type Albums = { id: number; artists_id: number; artist: string; name: string; cover_path: string; album_type: string; duration: number; track_count: number; year: number; path: string }
export type ArtistWithAlbums = { artist: Artists; albums: AlbumWithTracks[] }
export type Artists = { id: number; name: string; path: string }
export type MediaPayload = { Play: boolean } | { Pause: boolean } | { Next: boolean } | { Previous: boolean } | { Volume: number } | { Seek: number } | { Position: number }
export type PlayerState = "Playing" | "Paused"
export type Tracks = { id: number; duration: number; album: string; albums_id: number; artist: string; artists_id: number; name: string; path: string; cover_path: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
